name: check  # 工作流名称:资源检查

on:  # 触发工作流的条件
  push:
    branches:
      - "**"  # 推送到任意分支时触发
    paths:     # 只有这些文件改动时才触发
      - ".github/workflows/check.yml"  # 工作流配置文件改动
      - "assets/**"   # assets目录下的任意文件改动
      - "**.py"       # 任意Python文件改动
  pull_request:
    branches:
      - "**"   # PR提交到任意分支时触发
    paths:     # 只有这些文件改动时才触发
      - ".github/workflows/check.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  resource:  # 资源检查任务
    runs-on: macos-latest  # 在最新版macOS环境下运行
    steps:
      - uses: actions/checkout@v4  # 检出代码
        with:
          fetch-depth: 0  # 获取完整历史记录

      # 安装MAA框架Python包
      - name: Install maafw
        run: |
            python -m pip install --upgrade pip  # 更新pip
            python -m pip install --upgrade maafw --pre  # 安装最新预发布版本的maafw

      - name: Check Resource  # 检查资源文件
        run: |
            python ./tools/ci/check_resource.py ./assets/resource/  # 执行资源检查脚本
